version: "3"
services:
  api:
    build: .
    image: event-planner-api:latest
    ports:
      - "8080:8080"
    env_file:
      - .env.prod
    depends_on:
     - database
  database:
    image: mongo
    ports:
      - "27017"
    volumes:
      - data:/data/db
volumes:
  data: